---
# See also: roles/workstation/defaults/main/packages.yml

# Nested list of Gnome packages:
gnome_packages:
  - "{{ [
      'gnome-extensions-app',
      'gnome-shell-extension-appindicator',
    ]
    if (ansible_facts.os_family == 'RedHat') else [] }}"
  - "{{ [
      'gnome-shell-extension-blur-my-shell',
    ]
    if (ansible_facts.distribution == 'Fedora') else [] }}"
  - "{{ [
      'gnome-shell-extension-prefs',
      'gnome-shell-extensions',
    ]
    if (ansible_facts.os_family == 'Debian') else [] }}"
  - "{{ [
      'gnome-shell-ubuntu-extensions',
    ]
    if (ansible_facts.distribution == 'Ubuntu') else [] }}"
  - dconf-editor
  - gnome-control-center
  - gnome-screenshot
  - gnome-shell
  - gnome-text-editor  # gedit
  - gnome-tweaks
  - loupe  # eog
  - ptyxis  # gnome-terminal
  - seahorse
  - xdg-desktop-portal-gnome
  # Gnome extensions, some required by gnome-classic[-session]
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-user-theme
  - gnome-shell-extension-window-list

# Packages to remove from Gnome workstations (Fedora/Debian/Ubuntu):
# Use Flatpak to sandbox audio/video players and document viewers.
gnome_blacklisted_packages:
  # Fedora 39+ / Gnome 45+
  - "{{ [
      'fedora-chromium-config',
      'fedora-chromium-config-gnome',
      'fedora-chromium-config-gssapi',
      'gnome-shell-extension-background-logo',
    ]
    if (ansible_facts.distribution == 'Fedora') else [] }}"
  # Unwanted common Gnome packages
  - chrome-gnome-shell
  - decibels  # Gnome 50 Audio Player
  - eog  # loupe
  - gedit  # gnome-text-editor
  - gedit-common
  - gnome-boxes
  - gnome-browser-connector
  - gnome-calendar
  - gnome-connections
  - gnome-contacts
  - gnome-documents
  - gnome-epub-thumbnailer
  - gnome-maps
  - gnome-music
  - gnome-photos
  - gnome-terminal  # ptyxis
  - gnome-todo
  - gnome-tour
  - gnome-user-share
  - gnome-weather
  - papers  # Gnome 50 Document Viewer
  - papers-libs
  - papers-nautilus
  - papers-previewer
  - papers-thumbnailer
  - rhythmbox
  - shotwell
  - shotwell-common
  - showtime  # Gnome 50 Video Player
  - totem
  - totem-common
  - vinagre
  # Pre-installed games (Debian)
  - aisleriot
  - atomix
  - five-or-more
  - four-in-a-row
  - gnome-2048
  - gnome-chess
  - gnome-games
  - gnome-klotski
  - gnome-mahjongg
  - gnome-mines
  - gnome-nibbles
  - gnome-robots
  - gnome-sudoku
  - gnome-taquin
  - gnome-tetravex
  - hitori
  - iagno
  - lightsoff
  - quadrapassel
  - swell-foop
  - tali
