---
- name: Check SSH authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.key }}"
    key: "{{ item.value }}"
    exclusive: "{{ ssh_authorized_keys_exclusive }}"
  register: _ssh_authorized_keys_check
  with_dict: "{{ ssh_authorized_keys }}"
  check_mode: true

- name: Update changed SSH authorized keys
  when: _ssh_authorized_keys_check.changed
  block:
    - name: Reduce _ssh_authorized_keys_check to changed items
      ansible.builtin.set_fact:
        _ssh_authorized_keys_changed_items: "{{ _ssh_authorized_keys_check.results
          | selectattr('changed', 'equalto', true) }}"

    - name: Ensure changed authorized keys files are NOT immutable
      when: ssh_authorized_keys_immutable
      ansible.builtin.file:
        path: "{{ item }}"
        attr: "-i"
      with_items: "{{ _ssh_authorized_keys_changed_items | map(attribute='keyfile') }}"
      failed_when: false

    - name: Install SSH authorized keys
      ansible.posix.authorized_key:
        user: "{{ item.user }}"
        key: "{{ item.key }}"
        exclusive: "{{ item.exclusive }}"
      with_items: "{{ _ssh_authorized_keys_changed_items }}"

- name: Ensure authorized keys files are immutable
  when: ssh_authorized_keys_immutable
  ansible.builtin.file:
    path: "{{ item }}"
    attr: "+i"
  with_items: "{{ _ssh_authorized_keys_check.results | map(attribute='keyfile') }}"
  changed_when: _ssh_authorized_keys_check.changed
