---
# Unmanaged users retain their existing authorized_keys,
# there is no need to check lockout conditions here.

- name: Manage SSH authorized_keys files (default paths)
  ansible.posix.authorized_key:
    user: "{{ item.key }}"
    key: "{{ item.value }}"
    exclusive: "{{ ssh_authorized_keys_exclusive }}"
    manage_dir: true
  with_dict: "{{ ssh_authorized_keys }}"
