---
# In restricted containers, ssh_manage_packages should be true
# uninstall.yml tasks should run over disable.yml tasks.

- name: Disable sshd socket service
  when: "ansible_facts.service_mgr == 'systemd'"
  ansible.builtin.systemd:
    name: "{{ ssh_server_service_name }}.socket"
    state: "stopped"
    enabled: false
  register: _ssh_sshd_socket_result
  failed_when: "_ssh_sshd_socket_result.failed
    and not _ssh_sshd_socket_result.msg.startswith('Could not find ')"

- name: Disable sshd service
  ansible.builtin.service:
    name: "{{ ssh_server_service_name }}"
    state: "stopped"
    enabled: false
  register: _ssh_sshd_service_result
  failed_when: "_ssh_sshd_service_result.failed
    and not _ssh_sshd_service_result.msg.startswith('Could not find ')"
