---
- name: Ensure OpenSSH server is installed
  ansible.builtin.package:
    name: "{{ ssh_server_package }}"
    state: "present"
  notify: "Restart sshd service"

- name: Ensure SSH extra packages are installed
  ansible.builtin.package:
    name: "{{ ssh_extra_packages | flatten }}"
    state: "present"
