---
- name: SSH configuration tasks
  tags: [ssh]
  block:
    - name: Include SSH server install/uninstall/disable tasks
      when: ssh_manage_packages or ssh_server_disabled
      ansible.builtin.include_tasks:
        file: "{{ 'install.yml' if not ssh_server_disabled else 'uninstall.yml'
          if ssh_manage_packages else 'disable.yml' }}"

    - name: Include SSH authorized keys tasks
      when: ssh_authorized_keys_enabled
      ansible.builtin.include_tasks:
        file: authorized-keys.yml

    - name: Include SSH server config tasks
      when: not ssh_server_disabled and ssh_server_config_overridable
      ansible.builtin.include_tasks:
        file: server-config.yml

    - name: Run handlers immediately
      ansible.builtin.meta: flush_handlers

    - name: Ensure sshd is enabled if it should be
      when: not ssh_server_disabled
      ansible.builtin.service:
        name: "{{ ssh_server_service_name }}"
        state: "started"
        enabled: true

    - name: SSH role completed
      ansible.builtin.assert:
        that: true
        quiet: true
