---
- name: SSH configuration tasks
  tags: [ssh]
  block:
    - name: Include SSH configuration tasks
      ansible.builtin.include_tasks:
        file: "{{ (not ssh_server_disabled) | ternary('install', 'uninstall') }}.yml"

    - name: SSH role completed
      ansible.builtin.assert:
        that: true
        quiet: true
