---
- name: SSH configuration tasks
  tags: [ssh]
  block:
    - name: Include SSH server installation tasks
      when: ssh_manage_packages
      ansible.builtin.include_tasks:
        file: "{{ (not ssh_server_disabled) | ternary('install', 'uninstall') }}.yml"

    - name: Include SSH authorized_keys tasks
      when: ssh_authorized_keys_enabled
      ansible.builtin.include_tasks:
        file: "authorized-keys-{{ ssh_authorized_keys_immutable | ternary('immutable', 'default') }}.yml"

    - name: Include SSH server config tasks
      when: not ssh_server_disabled and ssh_server_config_overridable
      ansible.builtin.include_tasks:
        file: server-config.yml

    - name: Import SSH server reconciliation tasks
      ansible.builtin.import_tasks:
        file: server-reconciliation.yml

    - name: SSH role completed
      ansible.builtin.assert:
        that: true
        quiet: true
