---
namespace: oszi
name: general

# Versioned by _scripts/galaxy-release.sh
version: "4.55.0"

description: "Ansible collection for general, bite-sized, single-purpose roles."
repository: "https://github.com/oszi/ansible-collections.git"
readme: README.md

authors:
  - "David O. (oszi.dev)"
license:
  - "BSD-3-Clause"

# See also: requirements.yml (project root)
dependencies:
  "ansible.netcommon": ">=8.0"
  "ansible.posix": ">=2.0"
  "ansible.utils": ">=6.0"
  "community.crypto": ">=2.22"
  "community.general": ">=12.0"
  "community.libvirt": ">=2.0"
  "containers.podman": ">=1.16"
  "amazon.aws": ">=10.0"
  "oszi.utils": "==4.52.1"

tags:
  - general
  - linux
