---
# Skip libvirt setup and configuration?
# * Set to false for nested virtualization.
libvirt_disabled: "{{ ansible_facts.virtualization_role == 'guest' }}"

# Path for local executables
libvirt_local_bin_path: "{{ local_bin_path | default('/usr/local/bin', true) }}"

# Libvirt/QEMU + GUI packages on Fedora/Debian/Ubuntu:
# * Override in a non-graphical environment.
libvirt_packages:
  - "{{ [
      'libvirt',
      'libvirt-devel',
      'qemu-kvm',
      'qemu-system-aarch64',
      'guestfs-tools',
      'python3-libguestfs',
      'libxml2',
      'virt-install',
    ]
    if (ansible_facts.os_family == 'RedHat') else [] }}"
  - "{{ [
      'libvirt-clients',
      'libvirt-daemon-system',
      'libvirt-dev',
      'libguestfs-tools',
      'python3-guestfs',
      'libxml2-utils',
      'virtiofsd',
    ]
    if (ansible_facts.os_family == 'Debian') else [] }}"
  - "{{ 'qemu-user' if ansible_facts.distribution == 'Ubuntu' else 'qemu-user-static' }}"
  - fzf  # for virsh-usb and virt-viewer-fzf
  - libguestfs-rescue
  - libguestfs-xfs
  - python3-lxml
  - qemu-system-arm
  - qemu-system-x86
  - virt-manager
  - virt-viewer

# WARNING: Most of the libvirt commands are not idempotent.
# Use the following with caution.

# List of dicts of args for community.libvirt.virt:
# - command: ..., xml: ..., flags: ..., state: ..., uri: ..., autostart: true
# # virsh dumpxml --migratable domain # set "xml" with lookup file or template
libvirt_domains: []

# List of dicts of args for community.libvirt.virt_net:
# - command: ..., xml: ..., state: ..., uri: ..., autostart: true
libvirt_networks: []

# List of dicts of args for community.libvirt.virt_pool:
# - command: ..., xml: ..., mode: ..., state: ..., uri: ..., autostart: true
libvirt_pools: []
