---
- name: ACME tasks
  tags: [acme]
  block:
    - name: Include ACME tasks
      when: not acme_disabled
      ansible.builtin.include_tasks:
        file: acme.yml

    - name: ACME role completed
      ansible.builtin.assert:
        that: true
        quiet: true
