---
- name: Deploy rootless baselinux roles
  hosts: "{{ [rootless_baselinux_hosts | default('rootless'),
    rootless_containerhost_hosts | default('rootless_containerhosts'),
    rootless_workstation_hosts | default('rootless_workstations')] | flatten }}"
  become: false
  gather_facts: false
  roles:
    - oszi.utils.bootstrap
    - oszi.general.python
    - oszi.general.shell
    - oszi.general.dotfiles
    - oszi.general.cloudflare_dns
    - oszi.general.downloads
    - oszi.general.acme

- name: Deploy rootless containerhost roles
  hosts: "{{ [rootless_containerhost_hosts | default('rootless_containerhosts'),
    rootless_workstation_hosts | default('rootless_workstations')] | flatten }}"
  become: false
  gather_facts: false
  roles:
    - oszi.general.podman
    - oszi.general.podman_kube
    - oszi.general.podman_quadlets

- name: Deploy rootless workstation roles
  hosts: "{{ rootless_workstation_hosts | default('rootless_workstations') }}"
  become: false
  gather_facts: false
  roles:
    - oszi.general.flatpak
    - oszi.general.gnome_users
