---
# Exported for downstream roles to add shrc integrations
- name: Export shell role facts
  ansible.builtin.set_fact:
    shell_integrations_enabled: "{{ not shell_disabled }}"
    shell_integrations_shrc_d_path: "{{ shell_shrc_d_path }}"
    cacheable: true  # Persists through all plays.
