---
- name: Shell configuration tasks
  tags: [shell]
  block:
    - name: Export shell_shrc_d_export_path fact for integrations
      ansible.builtin.set_fact:
        shell_shrc_d_export_path: "{{ shell_shrc_d_path if not shell_disabled
          and ansible_facts.user_uid | int == 0 else none }}"
        cacheable: true
      tags: [always]

    - name: Include shell configuration tasks
      when: not shell_disabled
      ansible.builtin.include_tasks:
        file: shell.yml

    - name: Include tasks to enforce skeleton config files
      when: not shell_disabled
      ansible.builtin.include_tasks:
        file: skel-user.yml
      loop: "{{ shell_skeleton_enforced_users | unique }}"
      loop_control:
        loop_var: _shell_user_item_var  # use as shell_user_item

    - name: Shell role completed
      ansible.builtin.assert:
        that: true
        quiet: true
