---
- name: "Get info about user:{{ shell_user_item }}"
  ansible.builtin.user:
    name: "{{ shell_user_item }}"
    state: "present"
  # The user does not exist yet if changed!
  register: shell_user_info
  check_mode: true

# Newly created users will copy /etc/skel later.
- name: Enforce skel templates as the user itself for existing users
  become: true
  become_user: "{{ shell_user_item }}"
  when: "not shell_user_info.changed and shell_user_info | oszi.utils.is_login_user"
  block:
    - name: "Enforce skel templates for user:{{ shell_user_item }}"
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ [shell_user_info.home, item | basename | regex_replace('\\.j2$', '')] | path_join }}"
        owner: "{{ shell_user_info.uid }}"
        group: "{{ shell_user_info.group }}"
        mode: "0640"
      with_fileglob:
        - "templates/etc/skel/.*.j2"
