---
- name: Configure the shell environment
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Import bootstrap role
      ansible.builtin.import_role:
        name: oszi.utils.bootstrap

    # "locale" (rootful) is not a dependency of "shell" (rootless) but "shell" uses "locale" facts.
    - name: Import locale facts tasks
      ansible.builtin.import_role:
        name: oszi.general.locale
        tasks_from: facts
      tags: [always]

  roles:
    - oszi.general.shell
