---
# "locale" (rootful) is not a dependency of "shell" (rootless) but "shell" uses "locale" facts.
# This playbook is rootful so include both roles for full functionality.
- name: Configure the shell environment
  hosts: all
  become: true
  gather_facts: false
  roles:
    - oszi.utils.bootstrap
    - oszi.general.locale
    - oszi.general.shell
