---
# Path to install quadlet system units
podman_quadlets_systemd_path: "/etc/containers/systemd"

# Command to run podman-system-generator in dry-run mode
podman_quadlets_system_generator_dryrun: "/usr/lib/systemd/system-generators/podman-system-generator -dryrun"

# Supported quadlet types (extensions)
podman_quadlets_types:
  - artifact
  - build
  - container
  - image
  - kube
  - network
  - pod
  - volume

# Regex for fully-qualified quadlet names: NAME[@].TYPE
podman_quadlets_name_regex: "^\\w[\\w_-]*@?\\.(?:{{ '|'.join(podman_quadlets_types | map('regex_escape')) }})$"
