---
- name: Restart sshd service
  when: not ssh_server_disabled  # If triggered by sshd socket
  ansible.builtin.systemd:
    name: "{{ ssh_server_service_name }}.service"
    state: "restarted"
    enabled: true
    masked: false

- name: Ensure the configured SSH port is used
  ansible.builtin.set_fact:
    ansible_port: "{{ ssh_port }}"  # noqa: var-naming[no-role-prefix]
  listen: "Set ansible_port to ssh_port"

- name: Check connectivity
  ansible.builtin.ping:
  listen: "Set ansible_port to ssh_port"
