---
- name: Restart sshd service
  when: not ssh_server_disabled  # If triggered by sshd socket
  ansible.builtin.systemd:
    name: "{{ ssh_server_service_name }}.service"
    state: "restarted"
    enabled: true
    masked: false

- name: Ensure the configured SSH port is used
  ansible.builtin.set_fact:
    ansible_port: "{{ ssh_port }}"  # noqa: var-naming[no-role-prefix]
  listen: "Set ansible_port to ssh_port"

- name: Check connectivity
  ansible.builtin.ping:
  listen: "Set ansible_port to ssh_port"

# XXX: Kept for migrating away from immutable files. Remove in a few releases.
- name: Ensure home-dir relative authorized_keys files are NOT immutable
  when: ssh_authorized_keys_enabled and ssh_authorized_keys_immutable
  ansible.builtin.file:
    path: "~{{ item }}/.ssh/authorized_keys"
    attr: "-i"
  with_items: "{{ ssh_authorized_keys.keys() }}"
  changed_when: false
  failed_when: false
  listen: "Clean up home-dir relative authorized_keys files"

- name: Ensure home-dir relative authorized_keys files are absent
  when: ssh_authorized_keys_enabled and ssh_authorized_keys_immutable
  ansible.builtin.file:
    path: "~{{ item }}/.ssh/authorized_keys"
    state: "absent"
  with_items: "{{ ssh_authorized_keys.keys() }}"
  listen: "Clean up home-dir relative authorized_keys files"
