---
- name: Flatten package list variables
  ansible.builtin.set_fact:
    package_manager_extra_packages: "{{ package_manager_extra_packages | flatten }}"
    package_manager_blacklisted_packages: "{{ package_manager_blacklisted_packages | flatten }}"

- name: Ensure blacklisted packages are removed
  ansible.builtin.package:
    name: "{{ package_manager_blacklisted_packages }}"
    state: "absent"

- name: Ensure extra packages are installed
  ansible.builtin.package:
    name: "{{ package_manager_extra_packages | difference(package_manager_blacklisted_packages) }}"
    state: "present"
