---
- name: Package-manager update tasks
  when: not package_manager_disabled
  tags: [package-manager]
  block:
    - name: Update distribution packages
      ansible.builtin.package:
      args: "{{ package_manager_update_apt_args if ansible_facts.pkg_mgr == 'apt'
        else package_manager_update_dnf_args }}"

    - name: Autoremove orphaned packages
      when: package_manager_update_autoremove
      ansible.builtin.package:
        autoremove: true
