---
flatpak_remotes:
  flathub: "https://flathub.org/repo/flathub.flatpakrepo"

flatpak_apps:
  org.chromium.Chromium: flathub

# Tighten sandbox security!
flatpak_global_overrides:
  - "--nofilesystem=host"
  - "--nofilesystem=home"

flatpak_app_overrides:
  org.chromium.Chromium:
    - "--filesystem=xdg-download"

flatpak_exports_bin_aliases: "{{ _flatpak_exports_bin_aliases_all | dict2items
  | selectattr('value', 'in', flatpak_apps) | items2dict }}"

_flatpak_exports_bin_aliases_all:
  chromium: org.chromium.Chromium
  signal-desktop: org.signal.Signal
