---
# Redundantly runs per user but we do not want role-level facts for this.
# Do not skip if defined, the variable would be overridden by the skipped task.
# git-delta should be installed by oszi.general.shell
- name: Detect presence of git-delta
  ansible.builtin.shell: |
    set -euo pipefail
    command -v delta
  args:
    executable: /bin/bash
  register: _dotfiles_git_delta_command  # gitconfig.j2
  changed_when: false
  check_mode: false
  failed_when: false

- name: "Install git dotfiles for user:{{ dotfiles_user_item }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ dotfiles_user_info.home }}/.{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{ dotfiles_user_info.uid }}"
    group: "{{ dotfiles_user_info.group }}"
    mode: "0640"
  with_items:
    - "templates/dotfiles/gitconfig.j2"
    - "templates/dotfiles/gitignore.j2"
