---
namespace: oszi
name: environments

# Versioned by _scripts/galaxy-release.sh
version: "4.73.2"

description: "Ansible collection for personal, high-level environment roles."
repository: "https://github.com/oszi/ansible-collections.git"
readme: README.md

authors:
  - "David O. (oszi.dev)"
license:
  - "BSD-3-Clause"

dependencies:
  # Pinned by _scripts/galaxy-release.sh
  "oszi.general": "==4.73.2"
  "oszi.thirdparty": "==4.71.0"
  "oszi.utils": "==4.68.0"

tags:
  - environments
  - linux
