#!/bin/sh
# Automagical inventory selector for multiple isolated inventory files.
# Source this file in your terminal at the same level as the inventory directory.
# ANSIBLE_INVENTORY will take precedence over ansible.cfg - overridable with CLI arguments.

if ! [ -e ansible.cfg ] && [ -d ansible ]; then
    cd ansible || false
fi

if [ -d venv ]; then
    . venv/bin/activate
elif [ -d collections/venv ]; then
    . collections/venv/bin/activate
elif [ -d ../venv ]; then
    . ../venv/bin/activate
fi

if [ -n "${ANSIBLE_INVENTORY-}" ]; then
    echo "WARNING: Inventory already set!" >&2
    echo "ANSIBLE_INVENTORY=${ANSIBLE_INVENTORY}" >&2

elif [ -d inventory ]; then
    _ansible_inventories_found=$(
        find inventory -maxdepth 1 -type f -print0 \
            | xargs -0 -r grep --files-with-matches -- "$(hostname -f)" \
            | tr '\n' ',' | sed 's/,$//'
    )

    if [ "$_ansible_inventories_found" != "" ]; then
        export ANSIBLE_INVENTORY="$_ansible_inventories_found"
        echo "ANSIBLE_INVENTORY=${ANSIBLE_INVENTORY}" >&2
    else
        echo "WARNING: Host not found in the inventory! Using ansible.cfg" >&2
        true # Error in production.
    fi

else
    echo "ERROR: inventory directory not found!" >&2
    false
fi
