---
# Disable and uninstall(!) OpenSSH server?
ssh_server_disabled: "{{ ansible_facts.virtualization_type == 'container' }}"

# Space-separated list of one or more comma-separated authentication methods...
# publickey password hostbased keyboard-interactive none
ssh_auth_methods: "publickey"

# Dict of authorized keys by user
# Multiple keys can be separated by new lines, for example:
# from="0.0.0.0/0",restrict,pty ssh-ed25519 AAAA... mobile-biometric
# from="0.0.0.0/0",restrict,command="{{ ssh_sftp_subsystem }}" ssh-ed25519 AAAA... mobile-sftp-only
ssh_authorized_keys: {}
# Remove keys that were not configured here?
ssh_authorized_keys_exclusive: true
# Make authorized_keys files immutable to protect restrictions?
# NOTE: Without making ~/.ssh append-only (+a) this can still be worked around!
# But that breaks some legitimate use-cases - e.g. cleaning up control sockets.
ssh_authorized_keys_immutable: false

# Override the distro sshd_config?
ssh_server_config_overridable: true
# LogLevel directive in sshd_config
ssh_server_log_level: "VERBOSE"
# Extra lines for sshd_config
ssh_server_config_extra: ""
# List of SSH allowed users
ssh_allow_users: []
# List of SSH allowed groups
ssh_allow_groups: []

# Harden SSHD crypto settings?
ssh_harden_crypto: true
# Enable post-quantum algorithms?
ssh_harden_crypto_post_quantum_enabled: true
# Enable legacy RSA algorithms?
ssh_harden_crypto_rsa_enabled: "{{ ssh_host_keys | map('basename') | join(' ')
  | regex_search(ssh_host_key_regex_rsa) is not none }}"

# List of host keys (see ssh_host_key_regex_all):
ssh_host_keys:
  - /etc/ssh/ssh_host_ed25519_key
  # - /etc/ssh/ssh_host_rsa4096_key
