---
- name: "Get info about user:{{ dotfiles_user_item }}"
  ansible.builtin.user:
    name: "{{ dotfiles_user_item }}"
    state: "present"
  # The user does not exist yet if changed!
  register: dotfiles_user_info
  check_mode: true

- name: "Assert that the dotfiles user is valid"
  ansible.builtin.assert:
    that: ["not dotfiles_user_info.changed
      and not dotfiles_user_info.shell.endswith('/nologin')
      and dotfiles_user_info.home != '/'"]

- name: Run all tasks as the user itself
  become: "{{ ansible_user | default('') != dotfiles_user_item }}"
  become_user: "{{ dotfiles_user_item }}"
  block:
    - name: "Include gnupg dotfiles for user:{{ dotfiles_user_item }}"
      when: dotfiles_gnupg_enabled
      ansible.builtin.include_tasks:
        file: dotfiles/gnupg.yml

    - name: "Include git dotfiles for user:{{ dotfiles_user_item }}"
      when: dotfiles_git_enabled
      ansible.builtin.include_tasks:
        file: dotfiles/git.yml

    - name: "Include extra dotfiles for user:{{ dotfiles_user_item }}"
      when: "dotfiles_files | length > 0"
      ansible.builtin.include_tasks:
        file: dotfiles/files.yml
