---
- name: Ensure flatpak remotes are installed
  community.general.flatpak_remote:
    name: "{{ item.key }}"
    flatpakrepo_url: "{{ item.value }}"
    method: "{{ flatpak_method }}"
    state: "present"
  with_dict: "{{ flatpak_remotes }}"

- name: Ensure flatpak apps are installed
  community.general.flatpak:
    name: "{{ item.key }}"
    remote: "{{ item.value }}"
    method: "{{ flatpak_method }}"
    state: "present"
  with_dict: "{{ flatpak_apps }}"

- name: Ensure blacklisted flatpak apps are not installed
  community.general.flatpak:
    name: "{{ item }}"
    method: "{{ flatpak_method }}"
    state: "absent"
  with_items: "{{ flatpak_blacklisted_apps }}"

- name: Ensure app flatpak overrides are set
  ansible.builtin.command: >-
    flatpak override --{{ flatpak_method }} {% for option in item.value
    %} {{ option | quote }} {% endfor %} {{ item.key | quote }}
  with_dict: "{{ flatpak_app_overrides }}"
  changed_when: false

- name: Ensure global flatpak overrides are set
  ansible.builtin.command: >-
    flatpak override --{{ flatpak_method }} {% for option in flatpak_global_overrides
    %} {{ option | quote }} {% endfor %}
  changed_when: false

- name: Ensure flatpak/exports/bin is a directory
  ansible.builtin.file:
    path: "{{ flatpak_exports_bin_path }}"
    state: "directory"
    mode: "0755"

- name: Symlink aliases to apps in flatpak/exports/bin
  ansible.builtin.file:
    src: "{{ item.value }}"
    dest: "{{ flatpak_exports_bin_path }}/{{ item.key }}"
    state: "link"
    follow: false
    force: false
  with_dict: "{{ flatpak_exports_bin_aliases }}"

- name: Remove obsolete files from flatpak/exports/bin
  ansible.builtin.file:
    path: "{{ flatpak_exports_bin_path }}/{{ item }}"
    state: "absent"
  with_items: "{{ flatpak_exports_bin_aliases_absent }}"
