---
- name: Install shell aliases for flatpak apps
  when: flatpak_shell_aliases_path is truthy
  block:
    - name: Generate shell aliases for flatpak apps
      ansible.builtin.shell: |
        set -euo pipefail
        while IFS='' read -r app || [[ -n "$app" ]]; do
          flatpak info --{{ flatpak_method }} --show-metadata "$app" \
          | awk -v app="$app" '
            /^\[.+\]$/ {
              is_app = ($0 == "[Application]")
              next
            }
            is_app && /^command=/ {
              sub(/^command=/, "")
              print app "=" $0
              exit
            }
          ' ||:
        done
      args:
        stdin: "{{ flatpak_apps.keys() | join('\n') }}"
        executable: "/bin/bash"
      register: _flatpak_app_commands_result
      check_mode: false
      changed_when: false
      failed_when: false

    - name: Install shell aliases for flatpak apps
      ansible.builtin.copy:
        content: |
          # Ansible managed flatpak app to command aliases.
          # First wins on command collision.
          # shellcheck shell=sh
          if ! command -v flatpak >/dev/null 2>&1; then
              return
          fi
          {% for item in _flatpak_app_commands_result.stdout_lines %}

          {% if item | regex_search('^\\w[\\w/._-]*=\\w[\\w._-]*$') is not none %}
          {% set app, command = item.split('=', 1) %}
          if ! command -v {{ command }} >/dev/null 2>&1; then
              alias {{ command }}='flatpak run {{ app }}'
          fi
          {% else %}
          # REGEX FAILED
          {{ item | comment }}
          {% endif %}
          {% endfor %}
        dest: "{{ flatpak_shell_aliases_path }}"
        mode: "0644"
