#!/bin/sh
# shellcheck shell=sh disable=SC1090 # non-constant source
# ansible managed /etc/shrc for interactive shells

case $- in
    *i*) ;;
      *) return ;;
esac

source_glob() {
    for rc in "$@"; do
        if [ -r "$rc" ]; then
            . "$rc"
        fi
    done
    unset rc
}

source_glob /etc/shrc.d/*.sh

if [ -n "${BASH_VERSION-}" ]; then
    if [ -z "${POSIXLY_CORRECT-}" ]; then
        source_glob /etc/shrc.d/*.bash
    fi

elif [ -n "${ZSH_VERSION-}" ]; then
    source_glob /etc/shrc.d/*.zsh
fi
