#!/bin/sh
# shellcheck shell=sh disable=SC1090 # non-constant source
# shellcheck disable=SC3009 # in POSIX brace expansion is undefined
# ansible managed shrc for POSIX-compatible shells

case $- in
    *i*) ;;
      *) return ;;
esac

source_glob() {
    for rc do
        if [ -r "$rc" ]; then
            . "$rc"
        fi
    done
    unset rc
}

source_glob_sort() {
    IFS='
'
    # shellcheck disable=SC2046 # word splitting
    set -- $(printf '%s\n' "$@" | sort -u)
    unset IFS
    source_glob "$@"
}

if [ -n "${BASH_VERSION-}" ]; then
    if [ -z "${POSIXLY_CORRECT-}" ]; then
        source_glob_sort /etc/shrc.d/*.{sh,bash}
        return
    fi

elif [ -n "${ZSH_VERSION-}" ] && [ "$(emulate)" = "zsh" ]; then
    source_glob_sort /etc/shrc.d/*.{sh,zsh}
    return
fi

source_glob /etc/shrc.d/*.sh
