#!/bin/sh
# shellcheck shell=sh disable=SC1090 # non-constant source
# ansible managed shrc for POSIX-compliant shells

case $- in
    *i*) ;;
      *) return ;;
esac

source_glob() {
    for rc do
        if [ -r "$rc" ]; then
            . "$rc"
        fi
    done
    unset rc
}

source_glob_sort() {
    IFS='
'
    # shellcheck disable=SC2046 # word splitting
    set -- $(printf '%s\n' "$@" | sort -u)
    unset IFS
    source_glob "$@"
}

if [ -n "${ZSH_VERSION-}" ]; then
    source_glob_sort /etc/shrc.d/*.sh \
        /etc/shrc.d/*.zsh

elif [ -n "${BASH_VERSION-}" ] && [ -z "${POSIXLY_CORRECT-}" ]; then
    source_glob_sort /etc/shrc.d/*.sh \
        /etc/shrc.d/*.bash

else
    source_glob /etc/shrc.d/*.sh
fi
